config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :messages
  resources :senders
  resources :recievers
  resources :forms
  resources :users do
    collection do
      get :statistics
  end
end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user

  validates :service_type, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2}
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :validity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:user_id, :service_type, :price, :time, :validity)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
def service_type_options(selected)
		service_types={0=>"оплата звонков", 1=>"платные смайлы", 2=>"изменение логина"}
		options_for_select(service_types.map { |k, v| [v, k]}, selected)
	end

	def show_type(arg)
		hash={"0"=>"оплата звонков", "1"=>"платные смайлы", "2"=>"изменение логина"}
		a=hash[arg]	
	end
end

app/views/payments/_form.html.haml
= form_for @payment do |f|
  - if @payment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@payment.errors.count, "error")} prohibited this payment from being saved:"
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.select(:user_id, user_options(f.object.user_id))
  .field
    = f.label :service_type
    = f.select(:service_type, service_type_options(f.object.service_type))
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :time
    = f.datetime_select :time
  .field
    = f.label :validity
    = f.number_field :validity
  .actions
    = f.submit t('helpers.submit')

app/views/payments/edit.html.haml
%h1 
  = t('helpers.editing')
  = Payment.model_name.human

= render 'form'

= link_to t('helpers.show'), @payment
\|
= link_to t('helpers.back'), payments_path

app/views/payments/index.html.haml
%h1 
  =t('helpers.listing')
  =Payment.model_name.human(count: 2)

%table
  %thead
    %tr
      %th= Payment.human_attribute_name(:user)
      %th= Payment.human_attribute_name(:service_type)
      %th= Payment.human_attribute_name(:price)
      %th= Payment.human_attribute_name(:time)
      %th= Payment.human_attribute_name(:validity)
      %th
      %th
      %th

  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.user.login
        %td= show_type(payment.service_type)
        %td= payment.price
        %td= payment.time
        %td= payment.validity
        %td= link_to t('helpers.show'), payment
        %td= link_to t('helpers.edit'), edit_payment_path(payment)
        %td= link_to t('helpers.destroy'), payment, :method => :delete, :data => { :confirm => t('helpers.sure') }

%br

= link_to t('helpers.new'), new_payment_path

app/views/payments/new.html.haml
%h1 
  = t('helpers.new')
  = Payment.model_name.human(count: 100)

= render 'form'

= link_to t('helpers.back'), payments_path

app/views/payments/show.html.haml
%p#notice= notice

%p
  %b 
    = Payment.human_attribute_name(:user) + ":"
  = @payment.user.login
%p
  %b 
    = Payment.human_attribute_name(:service_type) + ":"
  = show_type(@payment.service_type)
%p
  %b 
    = Payment.human_attribute_name(:price) + ":"
  = @payment.price
%p
  %b 
    = Payment.human_attribute_name(:time) + ":"
  = @payment.time
%p
  %b 
    = Payment.human_attribute_name(:validity) + ":"
  = @payment.validity

= link_to t('helpers.edit'), edit_payment_path(@payment)
\|
= link_to t('helpers.back'), payments_path