config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :messages
  resources :senders
  resources :recievers
  resources :forms
  resources :users do
    collection do
      get :statistics
  end
end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:user_id, :description, :hobbies, :bad_habbits, :living, :target)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
	def living_options(selected)
		livings={0=>"своя квартира",1=>"съемная квартира",2=>"с родителями",3=>"общежитие"}
		options_for_select(livings.map { |k, v| [v, k]}, selected)
	end

	def bad_habbit_options(selected)
		bad_habbits={0=>"курение",1=>"алкоголь",2=>"наркотики", 3=>"нет" }
		options_for_select(bad_habbits.map { |k, v| [v, k]}, selected)
	end

	def target_options(selected)
		targets={0=>"пообщаться",1=>"стать друзьями",2=>"встречаться",3=>"ищу супруга(у)"}
		options_for_select(targets.map { |k, v| [v, k]}, selected)
	end

	def show_habbits(arg)
		hash={"0"=>"курение","1"=>"алкоголь","2"=>"наркотики", "3"=>"нет"}
		a=hash[arg]	
	end

	def show_living(arg)
		hash={"0"=>"своя квартира","1"=>"съемная квартира","2"=>"с родителями","3"=>"общежитие"}
		a=hash[arg]	
	end

	def show_target(arg)
		hash={"0"=>"пообщаться","1"=>"стать друзьями","2"=>"встречаться","3"=>"ищу супруга(у)"}
		a=hash[arg]	
	end
end

app/views/forms/_form.html.haml
= form_for @form do |f|
  - if @form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@form.errors.count, "error")} prohibited this form from being saved:"
      %ul
        - @form.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.select(:user_id, user_options(f.object.user_id))
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :hobbies
    = f.text_area :hobbies
  .field
    = f.label :bad_habbits
    = f.select(:bad_habbits, bad_habbit_options(f.object.bad_habbits))
  .field
    = f.label :living
    = f.select(:living, living_options(f.object.living))
  .field
    = f.label :target
    = f.select(:target, target_options(f.object.target))
  .actions
    = f.submit t('helpers.submit')

app/views/forms/edit.html.haml
%h1 
  = t('helpers.editing')
  = Form.model_name.human
= render 'form'

= link_to t('helpers.show'), @form
\|
= link_to t('helpers.back'), forms_path

app/views/forms/index.html.haml
%h1 
  =t('helpers.listing')
  =Form.model_name.human(count: 2)

%table
  %thead
    %tr
      %th= Form.human_attribute_name(:user)
      %th= Form.human_attribute_name(:description)
      %th= Form.human_attribute_name(:hobbies)
      %th= Form.human_attribute_name(:bad_habbits)
      %th= Form.human_attribute_name(:living)
      %th= Form.human_attribute_name(:target)
      %th
      %th
      %th

  %tbody
    - @forms.each do |form|
      %tr
        %td= form.user.login
        %td= form.description
        %td= form.hobbies
        %td= show_habbits(form.bad_habbits)
        %td= show_living(form.living)
        %td= show_target(form.target)
        %td= link_to t('helpers.show'), form
        %td= link_to t('helpers.edit'), edit_form_path(form)
        %td= link_to t('helpers.destroy'), form, :method => :delete, :data => { :confirm => t('helpers.sure') }

%br

= link_to t('helpers.new'), new_form_path

app/views/forms/new.html.haml
%h1 
  = t('helpers.new')
  = Form.model_name.human(count: 100)

= render 'form'

= link_to t('helpers.back'), forms_path

app/views/forms/show.html.haml
%p#notice= notice

%p
  %b 
    = Form.human_attribute_name(:user) + ":" 
  = @form.user.login
%p
  %b 
    = Form.human_attribute_name(:description) + ":"
  = @form.description
%p
  %b 
    = Form.human_attribute_name(:hobbies) + ":"
  = @form.hobbies
%p
  %b 
    = Form.human_attribute_name(:bad_habbits) + ":"
  = show_habbits(@form.bad_habbits)
%p
  %b 
    = Form.human_attribute_name(:living) + ":"
  = show_living(@form.living)
%p
  %b 
    = Form.human_attribute_name(:target) + ":"
  = show_target(@form.target)

= link_to t('helpers.edit'), edit_form_path(@form)
\|
= link_to t('helpers.back'), forms_path