config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :messages
  resources :senders
  resources :recievers
  resources :forms
  resources :users do
    collection do
      get :statistics
  end
end

end

app/models/sender.rb
class Sender < ActiveRecord::Base
  belongs_to :user
  has_many:messages, :dependent => :destroy
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  # GET /senders
  # GET /senders.json
  def index
    @senders = Sender.all
  end

  # GET /senders/1
  # GET /senders/1.json
  def show
  end

  # GET /senders/new
  def new
    @sender = Sender.new
  end

  # GET /senders/1/edit
  def edit
  end

  # POST /senders
  # POST /senders.json
  def create
    @sender = Sender.new(sender_params)

    respond_to do |format|
      if @sender.save
        format.html { redirect_to @sender, notice: 'Sender was successfully created.' }
        format.json { render :show, status: :created, location: @sender }
      else
        format.html { render :new }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senders/1
  # PATCH/PUT /senders/1.json
  def update
    respond_to do |format|
      if @sender.update(sender_params)
        format.html { redirect_to @sender, notice: 'Sender was successfully updated.' }
        format.json { render :show, status: :ok, location: @sender }
      else
        format.html { render :edit }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senders/1
  # DELETE /senders/1.json
  def destroy
    @sender.destroy
    respond_to do |format|
      format.html { redirect_to senders_url, notice: 'Sender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender
      @sender = Sender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sender_params
      params.require(:sender).permit(:user_id)
    end
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/_form.html.haml
= form_for @sender do |f|
  - if @sender.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sender.errors.count, "error")} prohibited this sender from being saved:"
      %ul
        - @sender.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/senders/edit.html.haml
%h1 Editing sender

= render 'form'

= link_to 'Show', @sender
\|
= link_to 'Back', senders_path

app/views/senders/index.html.haml
%h1 Listing senders

%table
  %thead
    %tr
      %th User
      %th
      %th
      %th

  %tbody
    - @senders.each do |sender|
      %tr
        %td= sender.user
        %td= link_to 'Show', sender
        %td= link_to 'Edit', edit_sender_path(sender)
        %td= link_to 'Destroy', sender, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sender', new_sender_path

app/views/senders/new.html.haml
%h1 New sender

= render 'form'

= link_to 'Back', senders_path

app/views/senders/show.html.haml
%p#notice= notice

%p
  %b User:
  = @sender.user

= link_to 'Edit', edit_sender_path(@sender)
\|
= link_to 'Back', senders_path